### ISSUE TITLE
Can you remain only one note?

### ISSUE THREAD

**Issue by hipanda888** [Ajatt-Tools/mergenotes#1]
Thank you for you addon, It cant merge 3 notes into 1 note,  It's really useful.

But afer merging ,  there still exit all the original notes,  I need to delete redundant notes, could you remain only one note?

Maybe you can refer to ohter similar addon:  1482505492

Thanks a lot.

**Comment by tatsumoto-ren** [comment]
Yes, I'm working on the feature. Unfortunately it's not ready yet.

**Comment by tatsumoto-ren** [comment]
I've added the option your requested. Please tell me if it works properly. Thank you for your feedback.

**Comment by hipanda888** [comment]
Wonderful，everything is OK.  Thanks for your update:)
