### ISSUE TITLE
Return to the top of the browser after a merge

### ISSUE THREAD

**Issue by homunet** [Ajatt-Tools/mergenotes#10]
Hi. 
I'm meeting a small trouble, but annoying one.

This is the image when I just to merge the notes.
I filtered my deck with some word and picked up all the notes that I have to merge.
<img width="1233" alt="Screenshot 2023-02-25 at 10 30 41" src="https://user-images.githubusercontent.com/17694709/221328744-6663636c-36d7-4cf9-860d-d64fa0ecbd0f.png">

This is just after when I execute a merge.
<img width="1071" alt="Screenshot 2023-02-25 at 10 30 56" src="https://user-images.githubusercontent.com/17694709/221328742-ecee3f79-3cd0-4d49-8af8-3b957cb08f72.png">

And this is the result after pushing a downward arrow key. If I push a up key, I get same result.
<img width="1084" alt="Screenshot 2023-02-25 at 10 31 13" src="https://user-images.githubusercontent.com/17694709/221328728-79505dd7-9925-403c-b0b1-d66d9a00813b.png">

I want move upward or downward from the line I merged. But the editor force me to go back to top of the list. After all, I have to go back again manually where I was working at.
This is acceptable when the number of the lines are small, but I have around a hundred pairs to merge. I have to scroll the list and find the next line to merge.

In the some previous version of this add on, this did not happen. Sorry. I do not know when this started to occur. 
Also I'm not sure this is due to your addon or Anki itself.

**Comment by tatsumoto-ren** [comment]
I tried the steps on my computer, and I can't really reproduce the effect. I selected two cards, merged them, then pressed the ⬇️ button on the keyboard, but it didn't return to the very top. Not sure how I can help.

**Comment by homunet** [comment]
こんにちは。お名前からすると日本の方でしょうか。
この度はお忙しい中ご検証いただきましてありがとうございました。
それでは当方でも他の環境でもって再現検証を行い、再現できるようであれば、また状況をお知らせさせていただきます。
こちらのプラグインには大変助けられております。作成者様のご努力には頭が下がります。今後ともありがたく利用させていただきます。

**Comment by homunet** [comment]
If you need me to write this in English, tell me so.

イシューの再オープン失礼いたします。
あれから検証を進めたところ私の環境で不具合発生に一定の法則性が発見されましたのでお知らせいたします。
・対象のノートを複数選択する場合の方向が上向きの場合に不具合が発生する
状態です。
ブラウザ上でマージの対象のノートを複数選択する際、あるノートをマウスクリックした後、それより下に位置するノートをシフトキーを押下しながらクリックして選択したとします。この状態でマージを実行した場合、その後でカーソルを移動させても、一番上の行には飛ばず、その行から前後に移動します。一方、１枚目のノートのクリックの後、それより上のノートを選択して、マージを実行すると、その後にカーソルキーを押下すると、一番上の行に飛びます。
ノートを複数選択する際に、マウスクリックでは無く、「あるノートを選択した後にシフトキーを押しながらカーソルを移動させる方法」でも同じで、下向きにカーソルキーを押して複数選択をした場合には問題が無いのですが、上向きにカーソルキーを押して複数選択した場合には、同様の問題が発生します。
お忙しい中恐縮ですが、ご確認いただければ幸いです。

**Comment by tatsumoto-ren** [comment]
>お名前からすると日本の方でしょうか。

偽名です。日本人とかじゃないです。

>If you need me to write this in English, tell me so.

どちらでも構いません。

> 不具合が発生する

こっちでもう一度試したら、やはり確認できます。

カードがブラウザでどのようにソートされているかによって、挙動が変わります。

**昇順でソートされている場合**:

* あるカードを選択して、その**下**のカードを選択し、マージを行うと、それから下向き（あるいは上向き）矢印ボタンを押すと、一番上の行に飛びます。
* あるカードを選択して、その**上**のカードを選択し、マージを行うと、それから下向き（あるいは上向き）矢印ボタンを押すと、特に異常なことは起きません。

**降順でソートされている場合**:

* カードを選択して、下のカードを選択すろと、マージを実行する。それからボタンを押すと、異常は起きません。
* カードを選択して、上のカードを選択すろと、マージを実行する。それからボタンを押すと、一番上の行に飛びます。

複雑な問題ですね。まだどうしたらいいか思いつきません。Anki本体のバグの可能性もありますね。そうならば、[Anki forum](https://forums.ankiweb.net/)で聞いたほうがいいかも。

**Comment by homunet** [comment]
Hi.
I believe that you are super fluent in using Japanese. It is very rare in foreigners to use kanjis as you wrote. I admire you.
And thank you very much for examining the problem. At this moment I do not have any good word to explain this issue in official Anki forum. If it comes to you any good idea to cope with this, please update the addon.
Thanks again.

**Comment by tatsumoto-ren** [comment]
I have attempted to work around this issue by selecting the last remaining card after merging. I hope this helps.
