### ISSUE TITLE
Could you add a option for "RETURN"

### ISSUE THREAD

**Issue by hipanda888** [Ajatt-Tools/mergenotes#2]
Dear author,

I have merged a lot of dialogue sentences, but all the sentences in a same line, It seems rather messy.  Could you please add a RETURN parameter？

By the way，according to description , cards are sorted by their "due number"  ,  Could you tell me where can I find the field "due number" ?   or  can support sorted by "sorted field" in the browser.

Thankds & Regards 
Hipanda.

**Comment by tatsumoto-ren** [comment]
You can sort cards by their `due number` in the Anki Browser, like this:
![screenshot](https://user-images.githubusercontent.com/69171671/101259647-f479bf00-3721-11eb-96ec-a095c85a16c1.png)

What do you mean by a `return` parameter? There's already an option to undo changes by pressing `Edit -> Undo`.

**Comment by hipanda888** [comment]
Hi, I have found the due number,  but It looks like unchangeable. If I want to adjust merge order, how can I do?

Sorry,  RETURN mean ENTER that can break item into next line,   for example:

![1](https://user-images.githubusercontent.com/62789168/101270410-c93fb000-37b3-11eb-9d02-c3f9a10e849b.png)

**Comment by tatsumoto-ren** [comment]
I understood the request. Basically there are two options to be added:
1) an ability to control merge order.
2) an option to insert some string between the merged fields.

I'm working on it. I think I'll release an update within a day.

**Comment by hipanda888** [comment]
Much appreciated , thank you :)

**Comment by tatsumoto-ren** [comment]
I've added a few new features to allow users to specify a field separator and reverse order of cards. Please tell me if it's what you needed.

**Comment by hipanda888** [comment]
Thanks for your update. I have tested paramete "field_separator" it work well and really convenient.

for the "reverse_order", Could you order by system default field "sorted field"?  thus, I can assign & edit content of field to realize user-define order.

![1](https://user-images.githubusercontent.com/62789168/101899824-6900a200-3be9-11eb-8902-1fec7dfbe58f.png)
![2](https://user-images.githubusercontent.com/62789168/101899832-6aca6580-3be9-11eb-84d4-0bae2fe66e3c.png)
![3](https://user-images.githubusercontent.com/62789168/101899833-6b62fc00-3be9-11eb-95c1-bb7594688af5.png)

**Comment by tatsumoto-ren** [comment]
Good idea! I'll look into it.

**Comment by tatsumoto-ren** [comment]
I've added an option to choose ordering in `Edit` → `Merge Fields Settings`.

**Comment by hipanda888** [comment]
Perfect!  Thanks for your continuing update.
This is the best addon for merge dialogue sensence.
I'll recommand this addon to my anki friends：）

**Comment by tatsumoto-ren** [comment]
Great! Thank you for your feedback!
