### ISSUE TITLE
Auto merge duplicate notes

### ISSUE THREAD

**Issue by Kenifornication** [Ajatt-Tools/mergenotes#3]
Hi,

Thank you for making this addon, it has been very helpful to me, and I love how particularly smart it is in dealing with duplicate data. I'm using Anki for language learning and it's not uncommon that decks contain the same information in different ways spread on multiple notes, so I'm merging mostly "duplicates". So I was wondering if it would be possible for you to add a feature to auto merge notes based on matching fields?

There is a [similar addon](https://github.com/quancs/Remove-Duplicate-Cards) that does something similar except it deletes notes instead of merging and that's not cool in terms of preserving data, I thought I'd link it in case it could be of help to you in implementing this.

If you can't or don't want to, I understand, and I appreciate the work you put in this addon already.

Thank you.

**Comment by tatsumoto-ren** [comment]
Hi, thank you for this great idea!

Currently, it is possible to mark duplicates with the standard Anki tools and then select the notes you need and merge them with the add-on.

 I think automating this would be helpful. Probably something like the built-in "find duplicates..." menu could do.

**Comment by Kenifornication** [comment]
Yeah I've been using the inbuilt "Find Duplicates" feature but it's time-consuming to do it by hand if you have a lot of notes.

I think if you don't want to change a lot about how the addon really works, you could just add a "Merge on matching fields" option in the menu under "Merge fields", where the user still has to select the notes but this option prompts him to choose the field to do the matching on, and then iterates through the selected cards. This way you would side-step the worry about which deck or filtering options.

I'm not sure if that's easier or more difficult than whatever you had in mind, but just throwing it out there.

Thank you for taking it into consideration, I appreciate it very much.

**Comment by tatsumoto-ren** [comment]
I think we're done now. The new button has been added.

![screenshot](https://user-images.githubusercontent.com/69171671/136308551-69415b22-bed3-41e6-8bb9-6668ea66907f.png)

Please feel free to test it and report any issues.
