### ISSUE TITLE
Allow true newline as field separator

### ISSUE THREAD

**Issue by ghost** [Ajatt-Tools/mergenotes#4]
Hey, this addon is super useful for someone restructuring 40 000 notes, so thanks for developing it!  
One minor request: Your field separator allows &lt;br>, but because of some transformations I'm doing with the merged cards, it would be easier if there was instead a true newline in the HTML source of the card. Would it be possible to add this, e.g. by using `\n`?

**Comment by tatsumoto-ren** [comment]
As far as I know, Anki doesn't display the `\n` character properly, but adding interpretation for this character is possible.

**Comment by ghost** [comment]
Yeah, that would be ideal. I'm not quite sure on how you're currently handling processing, but maybe it would be easiest to add a checkbox in the options menu that enabled parsing as a non-raw string, which should then allow using any escape sequence that python allows. (If that wouldn't work, I'm fine with just \n handling, but maybe this way of implementing it would be nice and flexible/featureful)

**Comment by tatsumoto-ren** [comment]
Since most people won't use `\n` as an actual separator, I'm just going to add interpretation for it.

**Comment by tatsumoto-ren** [comment]
I have updated the add-on. Please report any problems if you spot them.

**Comment by ghost** [comment]
For now, it seems to be working - thanks a bunch! <3

**Comment by ghost** [comment]
I've been using it extensively the last 2 days without problems, so Imma close this! :)
