### ISSUE TITLE
Can't order by Sort Field correctly

### ISSUE THREAD

**Issue by hipanda888** [Ajatt-Tools/mergenotes#5]
Hi, Expert,

I have been using this add-on for over 1 year, thanks for your excellent addon.

I have a lot of dialog sentences to merge, sentence order is very import.  But some times, it can work correctly, in other time it can't order by sort field.  it seems exist bug.  Could you help me to correct this bug? Thanks a lot.

follows:

![1](https://user-images.githubusercontent.com/62789168/143368269-7604b92c-7476-4460-8d94-b43ae78d72a8.jpg)

**Comment by tatsumoto-ren** [comment]
What about the reverse order checkbox? does it solve the issue?

**Comment by hipanda888** [comment]
> What about the reverse order checkbox? does it solve the issue?

I usually merge more than 4 sentences, and using “reverse” would cause confusion in conversation. So I usually number the “sort field" for each sentence before merging.

**Comment by tatsumoto-ren** [comment]
I can't quite catch that. When I tried, the sorting worked as expected. 

https://user-images.githubusercontent.com/69171671/143371960-1050e82a-76dc-4e2e-8b5a-5c7234df32c8.mp4

**Comment by hipanda888** [comment]
![1](https://user-images.githubusercontent.com/62789168/143375189-3b0b7f49-131c-4144-99e5-2ccdfff52f26.jpg)

after merge

![2](https://user-images.githubusercontent.com/62789168/143375197-25748fcd-9183-46dd-9982-09185252fc07.jpg)

**Comment by tatsumoto-ren** [comment]
This is funny. I think the way strings are sorted is different across platforms or versions of Anki. Did this behavior start recently, maybe after an update?

**Comment by hipanda888** [comment]
Thanks for your reply,  
I just updated the anki and merge note to the newest verson. 
It seems that the phenomenon of the problem has not changed before or after the upgrade.

This situation is not stable, some times, the merger is normal, but sometimes not normal.

**Comment by tatsumoto-ren** [comment]
I'll test it on Windows. Maybe it sorts differently.

**Comment by hipanda888** [comment]
Much appreciated, thank you:）

**Comment by tatsumoto-ren** [comment]
Just changed the way sorting works to resemble how Anki does it. Hope it is better than what was before.

**Comment by hipanda888** [comment]
Wonderful，it solved my big problem, thanks for your hard work :D
