### ISSUE TITLE
No option for merging cards (2+ duplicates

### ISSUE THREAD

**Issue by MeowskyxD** [Ajatt-Tools/mergenotes#8]

**Comment by MeowskyxD** [comment]
Hello,

i wanted to merge some cards, after I downloaded different pre-made decks. Unfortunately, it does not seem to work and there is no button to merge (see pic). Already restarted anki+PC and turned off all other add-ons. I'm using the most updated version.

![image](https://user-images.githubusercontent.com/102475400/160287514-a98c16c8-e86a-4bc3-8501-2007694d2b39.png)

**Comment by tatsumoto-ren** [comment]
It should work on Anki 2.1.48+. Go to `Tools -> Addons -> Check for updates` to make sure.

**Comment by MeowskyxD** [comment]
Thank you for your fast answer. You were right! It works now :)
