### ISSUE TITLE
Merging cards with longest due date

### ISSUE THREAD

**Issue by MeowskyxD** [Ajatt-Tools/mergenotes#9]
I really like this add-on, but now I have a different problem... I want to merge cards from 2 different decks* and keep the "due date" od these cards. Unfortunately, every time I merge them, the "due date" is only from the newer cards kept (so my merged cards are all with "due date"  NEW). I already tried to change my settings, but it doesn't want to work. I would be thankful if someone could help me.

* Further explanation: I have a self deck with Joyo Kanji and downloaded one from shared decks. My goal is to merge them or rather only a certain information like radicals (I already changed the note-type so it's the same as my Joyo deck and deleted all fields I don't need). I would like to keep my already studied due dates because I don't want to start over again.

**Comment by tatsumoto-ren** [comment]
This should be possible if you set ordering to `Due` and check `Reverse order`. If it doesn't work for you, the problem has to be investigated.

**Comment by tatsumoto-ren** [comment]
When it comes to kanji, you might be looking for something more effective like the the [JP1K method](https://tatsumoto.neocities.org/blog/jp1k-anki-deck.html).

**Comment by MeowskyxD** [comment]
> This should be possible if you set ordering to `Due` and check `Reverse order`. If it doesn't work for you, the problem has to be investigated.

I tried this and even restarted Anki after changing it, but it does not work for me.... these cards are also from year 1960 (how did they do it???)




> When it comes to kanji, you might be looking for something more effective like the the [JP1K method](https://tatsumoto.neocities.org/blog/jp1k-anki-deck.html).

Thank you very much and I really appreciate it! But I need to stick to my schedule because of the content, I need for exams in my master degree. All I want to do now is to take the mnemonics, lookalikes and radicals from the Kanji Damage shared deck and complement it with my cards. I have my own system for studying (started 2014) and just want to make some things easier.

**Comment by tatsumoto-ren** [comment]
Maybe we need to add a sorting method that sorts based on the length of the interval. I'll look into it.
